### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by codywarmbo** [schwifty42069/pmg#5] opened 2019-10-13 01:09 UTC
As of the last couple hours, I am getting 403'd on every channel. 

```
2019/10/12 20:00:12 [xTeVe] Streaming Status:      Playlist: M3U - Tuner: 0 / 1
2019/10/12 20:00:21 [xTeVe] Buffer:                true [xteve]
2019/10/12 20:00:21 [xTeVe] Buffer Size:           8192 KB
2019/10/12 20:00:21 [xTeVe] Channel Name:          USA
2019/10/12 20:00:21 [xTeVe] Client User-Agent:     Lavf/58.9.100
2019/10/12 20:00:22 [xTeVe] Streaming Status:      Playlist: M3U - Tuner: 1 / 1
2019/10/12 20:00:22 [xTeVe] Streaming Type:        [HLS / M3U8]
2019/10/12 20:00:22 [xTeVe] Streaming URL:         http://peer2.savitar.tv/USANetwork/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTAvMTEvMjAxOSA5OjA2OjAxIFBNJmhhc2hfdmFsdWU9cTFaTnQrYmpDTFgxcDhtdkNMVjNydz09JnZhbGlkbWludXRlcz0zNjAmaWQ9MA==
2019/10/12 20:00:22 [xTeVe] Content Type:          text/html
2019/10/12 20:00:22 [xTeVe] Streaming Status:      HTTP Response Status [403] Forbidden
2019/10/12 20:00:22 [xTeVe] Error with this URL:   http://peer2.savitar.tv/USANetwork/myStream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTAvMTEvMjAxOSA5OjA2OjAxIFBNJmhhc2hfdmFsdWU9cTFaTnQrYmpDTFgxcDhtdkNMVjNydz09JnZhbGlkbWludXRlcz0zNjAmaWQ9MA==
2019/10/12 20:00:22 [xTeVe] [ERROR] Forbidden (This error message comes from the provider) - EC: 4004
```

**Comment by schwifty42069** [comment] 2019-10-13 01:50
The script needs to be rerun every 6 hours to refresh the wmsAuth token, did you try rerunning it?

If you have rerun the script, what version of the script are you using?

**Comment by codywarmbo** [comment] 2019-10-13 02:50
Yes I have re-run the script. I'm not sure how to check which version I used, but I downloaded it within the last few days. I believe I spoke to you on reddit. I used this guide: https://sites.google.com/view/piptv-plex/home

**Comment by schwifty42069** [comment] 2019-10-13 03:15
You can try updating with

```
pip install -U piptv_pmg.pmg
```

Try rerunning the script and playing the m3u in a player like VLC. I am running all the streams without issue right now, so if it works in a different player for you, it's unfortunately probably a plex/xteve config issue, which I can't really help with :/

**Comment by codywarmbo** [comment] 2019-10-13 03:35
Thanks. I actually deleted the whole thing and just reinstalled and also made some changes in xTeVe. I'm pretty sure reinstalling this is what fixed it.

**Comment by codywarmbo** [comment] 2019-10-15 21:03
Unfortunately I'm back in the same boat with the 403 errors. Deleting the .m3u produced did not help this time.

**Comment by schwifty42069** [comment] 2019-10-16 21:38
If you're not running the latest version of the script, update it. 

```
pip install -U piptv_pmg
```

If you are, try running the m3u generated by the script in VLC or any other media player and see if it works. I will leave this open to give you a chance to respond, but this isn't an issue with the script, it still works on every machine in my house and the site it scrapes hasn't changed anything in it's configuration that would break the script, which means it's likely an error in your configuration. 

See if you can reach the [site](http://ustvgo.tv/nfl-network-live-free) itself within a browser also, they may be blocking your ISP.

**Comment by codywarmbo** [comment] 2019-10-17 17:04
I have updated. The .m3u does not work in VLC or PotPlayer, I get a forbidden error in them. I am able to reach the site via browser. 

This issue is sporadic at this point now, it works for an hour or so and then reverts back to this issue.

**Comment by schwifty42069** [comment] 2019-10-17 17:25
Well, the fact that it is sporadic is evidence that it's either your config or your ISP, unfortunately. With that being said I can't really help you. If the script is the latest version and it runs without error then the problem is somewhere else down the line :/

If the script starts throwing an exception, open another issue, but I am going to close this one. I hope you figure out what's going on!

**Closed as completed by schwifty42069** 2019-10-17 17:25 UTC
