### ISSUE TITLE
Error with Ubuntu 18.04

### ISSUE THREAD

**Issue by heccoder** [schwifty42069/pmg#3] opened 2019-10-06 01:37 UTC
Getting the following error with Ubuntu 18.04 and python 3.6.8:

```
Detected Linux...

Working some black magic..

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 153, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 146, in main
    mw.retrieve_new_token()
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 101, in retrieve_new_token
    self.wms_auth_token.update({req['queryString'][0]['name']: req['queryString'][0]['value']})
TypeError: 'NoneType' object is not subscriptable
```

**Comment by heccoder** [comment] 2019-10-06 02:32
I just tried to remove and reinstall the package and requirements, now getting a different error:
```

Detected Linux...

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 153, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 145, in main
    mw = M3UWriter(write_dir)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 62, in __init__
    self.driver = webdriver.Firefox(self.profile, options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```
I am running this with `sudo` as cannot install the package due to permissions.

**Comment by schwifty42069** [comment] 2019-10-06 04:23
You can't run it as sudo, geckodriver forbids it. I should have put that in the docs.  

Go ahead and Install it with pip:

```
python3 -m pip install piptv_pmg
```

Run it as a module in a directory owned by the standard user account e.g */home/yourusername*  so that you don't need to be root to write to the directory like so:

```
python3 -m piptv_pmg.pmg -o /desired/outputdir/filename.m3u
```

That should take care of it. I will leave this open for a bit to give you a chance to respond.

**Comment by heccoder** [comment] 2019-10-06 04:35
I initially tried installing with my user but kept getting a permissions error, I just tried again and this is the output:

```
➜  ~ python3 -m pip install piptv_pmg
Collecting piptv_pmg
  Using cached https://files.pythonhosted.org/packages/b5/3b/bcc05f100cbfc1d6480e09b326527ccfcfc3b1ad0770c8cb57fd96e661c3/piptv_pmg-0.1.1-py3-none-any.whl
Collecting selenium==3.141.0 (from piptv_pmg)
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools==41.2.0 in /usr/local/lib/python3.6/dist-packages (from piptv_pmg)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/dist-packages (from selenium==3.141.0->piptv_pmg)
Installing collected packages: selenium, piptv-pmg
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.6/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.6/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/selenium'
```

**Comment by schwifty42069** [comment] 2019-10-06 04:49
You can install it as root, you just can't run it as root. My bad for not clarifying.

**Comment by schwifty42069** [comment] 2019-10-06 16:02
Closing this as it's nothing related to the script itself. If you can't get it running. open another issue

**Comment by heccoder** [comment] 2019-10-06 16:53
Sorry, I have followed your instructions: installed with sudo and run it with my user, still getting the same error on my initial post:
```

Detected Linux...


Working some black magic..

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 153, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 146, in main
    mw.retrieve_new_token()
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 101, in retrieve_new_token
    self.wms_auth_token.update({req['queryString'][0]['name']: req['queryString'][0]['value']})
TypeError: 'NoneType' object is not subscriptable
```

**Comment by schwifty42069** [comment] 2019-10-06 22:02
Can you reach the site by itself? It's http://ustvgo.tv/nfl-network-live-free

In a browser I mean. It seems like you're getting blocked, or it's trying to export before the page is finished loading.

**Comment by heccoder** [comment] 2019-10-07 01:36
Yes, I can access the site and stream content, I tried different channels and all worked.

**Comment by schwifty42069** [comment] 2019-10-07 03:47
You must have a really slow internet connection or pc because I can't reproduce this in Ubuntu 18.04 or any other distro for that matter, can you try adding the following after line 100 and rerunning the script? Make sure it is lined up exactly with the lines above and below it

```
import time
time.sleep(5)
```

You can find the script  at _/usr/local/lib/python3.6/dist-packages/piptv_pmg_

**Comment by heccoder** [comment] 2019-10-07 14:35
Thank you. I don't think is my internet (I have gig fiber) nor my PC, but I added the line and got a different error now:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 155, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 148, in main
    mw.retrieve_new_token()
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 100, in retrieve_new_token
    req = self.driver.execute_script(self.export_har_js)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: ReferenceError: HAR is not defined
```

I looked at another closed/resolved issue and added the code you mentioned, but still getting an error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 156, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 149, in main
    mw.retrieve_new_token()
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 104, in retrieve_new_token
    self.wms_auth_token.update({req['queryString'][0]['name']: req['queryString'][0]['value']})
TypeError: 'NoneType' object is not subscriptable
```

Not sure what I am doing wrong, but thank you for looking into it.

**Comment by schwifty42069** [comment] 2019-10-07 16:53
Damn man.. I have no idea what is going on, that's so weird. The 'NoneType' error basically means that it didn't see a request that contained the "m3u8" text that the injected javascript snippet is looking for. So  it's not beginning to load the actual hotlink for one reason or another.. Can you make sure you' re using version 0.1.1 of the script, and tell me what version of firefox you have installed?

**Comment by swratten** [comment] 2019-10-07 23:31
I'm having the exact same issue on my Fedora Server. Applied the same fix for:
``` selenium.common.exceptions.JavascriptException: Message: ReferenceError: HAR is not defined ```
and I am receiving the same error:
``` in retrieve_new_token
    self.wms_auth_token.update({req['queryString'][0]['name']: req['queryString'][0]['value']})
TypeError: 'NoneType' object is not subscriptable ```

**Comment by schwifty42069** [comment] 2019-10-08 00:13
I honestly can't troubleshoot this any further without more information. I haven't seen this on any Debian based distros or Windows, and I am unable to reproduce it under any conditions. I need to know what version of the script you're running, and I need a copy of the geckodriver.log that was created when the script was run. It's some weird flukey thing if it's finding the export HAR addon, installing it and executing it, but not getting anything back.

**Comment by schwifty42069** [comment] 2019-10-08 00:47
Also, Can you guys try opening firefox, pressing Ctrl+Shift+E which will open the network tab of firefox devtools  navigating to http://ustvgo.tv/nfl-network-live-free *without* clicking the play button in the player and typing m3u in the search bar that says "filter urls".. If the hotlink is loading up when the page loads (which it should) then you're okay, if it's not then that's why you're getting the NoneType error. I have tried and tried to reproduce the 'NoneType' return you guys are getting, but I can't.

**Comment by schwifty42069** [comment] 2019-10-08 00:52
I also will be refactoring this soon to move away from using the har export trigger addon all together as it seems to be really inconsistent and I know of a way I can get the exact same data it does and probably more efficiently.

**Comment by swratten** [comment] 2019-10-08 01:10
> Also, Can you guys try opening firefox, pressing Ctrl+Shift+E (which will open the network tab of firefox devtools), navigating to http://ustvgo.tv/nfl-network-live-free _without_ clicking the play button in the player and typing m3u in the search bar that says "filter urls".. If the hotlink is loading up when the page loads (which it should) then you're okay, if it's not then that's why you're getting the NoneType error. I have tried and tried to reproduce the 'NoneType' return you guys are getting, but I can't.

I'm running a headless server.. so might not be so easy to get network responses.

> I honestly can't troubleshoot this any further without more information. I haven't seen this on any Debian based distros or Windows, and I am unable to reproduce it under any conditions. I need to know what version of the script you're running, and I need a copy of the geckodriver.log that was created when the script was run. It's some weird flukey thing if it's finding the export HAR addon, installing it and executing it, but not getting anything back.

I've tried the 0.1.1 and 0.1.0 versions of your script.
I'll give you some more information:
```
$ firefox --version
Mozilla Firefox 69.0.1

$ uname -a
Linux fedora-media-server 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Geckolog:
https://paste.fedoraproject.org/paste/qRH84Uzmt0K8loVAc1aqYQ

**Comment by schwifty42069** [comment] 2019-10-08 02:21
I just refactored it to remove the need for the har export trigger addon all together, so please upgrade by doing the following:

```
python3 -m pip install -U piptv_pmg
```

Hopefully this will resolve it, it tests out fine for me.

**Comment by schwifty42069** [comment] 2019-10-08 02:23
Have you ever successfully used a script that makes use of selenium on that headless server? Because if the patch I just pushed doesn't fix it, you might be SOL brother.

**Comment by swratten** [comment] 2019-10-08 02:30
> Have you ever successfully used a script that makes use of selenium on that headless server? Because if the patch I just pushed doesn't fix it, you might be SOL brother.

It was already installed on the machine so I would assume something on my server has been using it.

**Comment by swratten** [comment] 2019-10-08 02:31
> I just refactored it to remove the need for the har export trigger addon all together, so please upgrade by doing the following:
> 
> ```
> python3 -m pip install -U piptv_pmg
> ```
> 
> Hopefully this will resolve it, it tests out fine for me.

I'll have to take a look when I'm home, looks like my internet has gone down there.

**Comment by schwifty42069** [comment] 2019-10-08 02:34
Damn alright. Haha let me know man. Kind of glad you guys had this issue, as it forced me to do a refactor that I should have done already, so thank you, and I'm sorry about this.

**Comment by heccoder** [comment] 2019-10-08 02:34
> I just refactored it to remove the need for the har export trigger addon all together, so please upgrade by doing the following:
> 
> ```
> python3 -m pip install -U piptv_pmg
> ```
> 
> Hopefully this will resolve it, it tests out fine for me.

I just updated to the latest version and ran it again, this time it worked! It generated the .m3u file. I have not tested streaming yet but the script seemed to have worked. Thank you!

**Comment by schwifty42069** [comment] 2019-10-08 02:35
@hjtech Thank the lord lolol. Sorry guys, that addon has been a pain in the ass the whole time, should have refactored it before I released the script.

**Comment by schwifty42069** [comment] 2019-10-08 02:39
I will leave this open for you @swratten so you can let me know if this resolved it for you too!

**Comment by heccoder** [comment] 2019-10-08 02:40
> @hjtech Thank the lord lolol. Sorry guys, that addon has been a pain in the ass the whole time, should have refactored it before I released the script.

No worries! Thank you for such a great script. I'll keep you posted if anything.

**Comment by schwifty42069** [comment] 2019-10-08 02:44
No problem! Thanks for your patience. Look out for my next couple of  releases. Writing what will essentially be a free NFL Sunday ticket script, as well as a piptvod script (for on demand movies/tv-shows)!

**Comment by swratten** [comment] 2019-10-08 04:12
> No problem! Thanks for your patience. Look out for my next couple of releases. Writing what will essentially be a free NFL Sunday ticket script, as well as a piptvod script (for on demand movies/tv-shows)!

Thanks for helping the community! I'm going to be using this particular script with a cron job so I can feed it to my Jellyfin server and use it as Live TV m3u provider. 
If you'd like I'll inform that community of my findings if it all goes well? :)

**Comment by swratten** [comment] 2019-10-08 06:10
> I will leave this open for you @swratten so you can let me know if this resolved it for you too!

Thanks I can now confirm that it works flawlessly :)

**Comment by schwifty42069** [comment] 2019-10-08 06:35
Of course that would be great! Don't be afraid to give the repo a star either ;D

Thanks again for hanging in there!

**Closed as completed by schwifty42069** 2019-10-08 06:35 UTC
